zuul:
  routes:
    catalogo:
      path: /productos/**
      service-id: servicio.productos
    compra:
      path: /compra/**
      service-id: servicio.carro
eureka:
  client:
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 6565
 
#Basic configuration SLF4j for development
#logging:
  #level:
   # org.springframework: ERROR
  #  com.bardalez: DEBUG
 # pattern:
  #  console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  #  file: "%d %p %c{1.} [%t] %m%n"
 # file: app.log
  
#Configuration SLF4j for production (logback-spring.xml)
spring:
  profiles:
    active:
    - default
